# NEWPATH="$HOME/.local/bin":$PATH
# export PATH=$NEWPATH
export EDITOR="nvim"
export PYTHON_HISTORY="$HOME/.cache/py_hist"
export GOPATH="$HOME/.cache/go"
export GNUPGHOME="$HOME/.local/share/gnupg"
export npm_config_cache="$HOME/.cache/npm"
export CARGO_HOME="$HOME/.cache/cargo"
export RUSTUP_HOME="$HOME/.local/opt/rustup"
# export MANPAGER='nvim +Man!'
export ACCENT_COLOR="A7C080"
