;; -*- lexical-binding: t; -*-
(deftheme fuuted
  "Custom theme that will be autogenerated with tmg so it fit with the current theme.")

(let ((bg0            "#0D0D0D")
      (bg-1           "#0D0D0D")
      (bg+1           "#2A2A2A")
      (bg+2           "#A8A8A8")
      (bg+3           "#C4C4C4")
      (bg+4           "#E0E0E0")
      (fg             "#E0E0E0")
      (fg+1           "#E0E0E0")
      (accent         "#B3A57F")

      ;; Normal
      (blue           "#6C7F9C")
      (green          "#70846D")
      (cyan           "#727A78")
      (red            "#B24B46")
      (magenta        "#8B7A90")
      (yellow         "#A3926F")

      ;; Bright
      (bright-cyan    "#919C97")
      (bright-green   "#869D86")
      (bright-yellow  "#B3A57F")
      (bright-magenta "#A493A4")
      (bright-blue    "#7C93B0")

      ;; extra stuff
      (bg-ui-select   "#1C1C1C")
      (bg-ui-select+1 "#2D2D2D")
      (yellow-comment "#766A52")
      )

  (custom-theme-set-variables
   'fuuted
   '(frame-background-mode (quote dark)))

  (custom-theme-set-faces
   'fuuted

   ;; --- Basic UI ---
   `(default ((t (:foreground ,fg :background ,bg0))))
   `(cursor ((t (:background ,accent ))))
   `(region ((t (:background ,bg-ui-select+1 :foreground nil))))
   `(secondary-selection ((t (:background ,bg+3))))
   `(mode-line ((t (:background ,bg+1 :foreground ,fg+1))))
   `(mode-line-inactive ((t (:background ,bg0 :foreground ,bg+3))))
   `(fringe ((t (:background ,bg0 :foreground ,bg+1))))
   `(vertical-border ((t (:foreground ,bg+1))))
   `(minibuffer-prompt ((t (:foreground ,cyan :weight bold))))
   `(link ((t (:foreground ,blue :underline t))))
   `(link-visited ((t (:foreground ,magenta :underline t))))
   `(tooltip ((t (:background ,bg+4 :foreground ,fg+1))))
   `(shadow ((t (:foreground ,bg+2))))

   ;; --- Syntax Highlighting (Font Lock) ---
   `(font-lock-builtin-face ((t (:foreground ,bright-cyan))))
   `(font-lock-comment-face ((t (:foreground ,yellow-comment))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,yellow-comment))))
   ;; `(font-lock-comment-face ((t (:foreground ,bright-yellow))))
   ;; `(font-lock-comment-delimiter-face ((t (:foreground ,bright-yellow))))
   `(font-lock-constant-face ((t (:foreground ,magenta))))
   `(font-lock-doc-face ((t (:foreground ,bright-green))))
   `(font-lock-doc-string-face ((t (:foreground ,bright-green))))
   `(font-lock-function-name-face ((t (:foreground ,blue))))
   `(font-lock-keyword-face ((t (:foreground ,yellow :bold t))))
   `(font-lock-string-face ((t (:foreground ,green))))
   `(font-lock-type-face ((t (:foreground ,cyan))))
   `(font-lock-variable-name-face ((t (:foreground ,fg+1))))
   `(font-lock-warning-face ((t (:foreground ,red :weight bold))))
   `(font-lock-preprocessor-face ((t (:foreground ,bright-blue))))

   ;; --- Whitespace ---
   `(whitespace-trailing ((t (:background ,bg+1 :foreground ,bg+2))))
   `(whitespace-space ((t (:background ,bg0 :foreground ,bg+1))))
   `(whitespace-tab ((t (:background ,bg0 :foreground ,bg+1))))
   `(whitespace-newline ((t (:background ,bg0 :foreground ,bg+1))))
   `(whitespace-line ((t (:background ,bg+1 :foreground ,red))))
   `(whitespace-empty ((t (:background ,bg+1 :foreground ,bg+1))))
   `(whitespace-indentation ((t (:background ,bg0 :foreground ,bg+1))))
   `(whitespace-space-after-tab ((t (:background ,bg0 :foreground ,bg+1))))
   `(whitespace-space-before-tab ((t (:background ,bg0 :foreground ,bg+1))))
   `(trailing-whitespace ((t (:background ,red))))

   ;; -- Vertico bullshit --
   `(vertico-current ((t (:background ,bg-ui-select+1 :foreground ,fg))))

   ;; --- Parenthesis ---
   `(show-paren-match ((t (:background ,bright-cyan :foreground ,bg0 :weight bold))))
   `(show-paren-mismatch ((t (:background ,red :foreground ,fg+1))))

   ;; --- Company (Completion) ---
   `(company-tooltip ((t (:background ,bg+1 :foreground ,fg))))
   `(company-tooltip-selection ((t (:background ,bg-ui-select :foreground ,fg))))
   `(company-tooltip-common ((t (:foreground ,yellow))))
   `(company-preview ((t (:foreground ,bg+2))))

   ;; --- Corfu ---
   `(corfu-default ((t (:background ,bg+1 :foreground ,fg))))
   `(corfu-current ((t (:background ,bg-ui-select :foreground ,fg))))
   `(corfu-annotations ((t (:foreground ,yellow))))
   `(corfu-border ((t (:background ,bg+2))))
   `(corfu-bar ((t (:background ,yellow))))

   ;; --- Compilation status (mode-line) ---
   `(compilation-mode-line-fail ((t (:foreground ,red :weight bold))))
   `(compilation-mode-line-exit ((t (:foreground ,green :weight bold))))
   `(compilation-mode-line-run ((t (:foreground ,yellow :weight bold))))

   ;; --- Magit ---
   `(magit-branch ((t (:foreground ,blue))))
   `(magit-diff-hunk-header ((t (:background ,bg+1))))
   `(magit-diff-file-header ((t (:background ,bg+2))))
   `(magit-log-sha1 ((t (:foreground ,red))))
   `(magit-log-author ((t (:foreground ,bright-yellow))))
   `(magit-item-highlight ((t (:background ,bg+1))))

   ;; --- Org Mode ---
   `(org-level-1 ((t (:foreground ,blue :weight bold))))
   `(org-level-2 ((t (:foreground ,cyan :weight bold))))
   `(org-level-3 ((t (:foreground ,magenta :weight bold))))
   `(org-todo ((t (:foreground ,red :weight bold))))
   `(org-done ((t (:foreground ,green :weight bold))))
   `(org-column ((t (:background ,bg-1))))

   ;; --- Compilation ---
   `(compilation-info ((t (:foreground ,green))))
   `(compilation-warning ((t (:foreground ,yellow :weight bold))))
   `(compilation-error ((t (:foreground ,red))))

   ;; --- Search ---
   `(isearch ((t (:foreground ,bg0 :background ,accent))))
   `(isearch-fail ((t (:foreground ,fg :background ,red))))
   `(lazy-highlight ((t (:background ,green :foreground, bg0))))
   `(match ((t (:background ,accent :foreground, bg0))))

   ;; --- Terminal (vterm/ansi) ---
   `(term-color-black   ((t (:foreground ,bg+2 :background ,bg+3))))
   `(term-color-red     ((t (:foreground ,red :background ,red))))
   `(term-color-green   ((t (:foreground ,green :background ,green))))
   `(term-color-bright-yellow  ((t (:foreground ,yellow :background ,yellow))))
   `(term-color-blue    ((t (:foreground ,blue :background ,blue))))
   `(term-color-magenta ((t (:foreground ,magenta :background ,magenta))))
   `(term-color-cyan    ((t (:foreground ,cyan :background ,cyan))))
   `(term-color-white   ((t (:foreground ,fg :background ,fg+1))))

   ;; --- Ido ---
   `(ido-first-match ((t (:foreground ,yellow :weight bold))))
   `(ido-only-match ((t (:foreground ,green :weight bold))))
   `(ido-subdir ((t (:foreground ,blue))))
   `(ido-indicator ((t (:foreground ,red :background ,bg0))))
   `(ido-virtual ((t (:foreground ,bright-yellow))))

   ;; --- Misc ---
   `(line-number ((t (:inherit default :foreground ,bg+2 :background ,bg0 :weight normal :slant normal :underline nil :strike-through nil))))
   `(line-number-current-line ((t (:inherit line-number :foreground ,yellow :background ,bg0 :weight bold))))
   `(header-line ((t (:background ,bg+1 :foreground ,fg))))
   `(tab-bar ((t (:background ,bg-1 :foreground ,bg+3))))
   `(tab-bar-tab ((t (:background ,bg0 :foreground ,yellow :weight bold))))
   ))

(provide-theme 'fuuted)
